# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "random_password/version"

Gem::Specification.new do |s|
  s.name        = "random_password"
  s.version     = RandomPassword::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Michael He"]
  s.email       = ["hlxwell@gmail.com"]
  s.homepage    = ""
  s.summary     = %q{Generate a password based on time and key, then match the password generated by iphone.}
  s.description = %q{Generate a password based on time and key, then match the password generated by iphone.}

  s.rubyforge_project = "random_password"

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
end